### ISSUE TITLE
Use nonEmptyListOf function instead of NonEmptyList constructor in arrow-0.13.1

### ISSUE THREAD

**Issue by ReaktorDTR** [kotest/kotest-assertions-arrow#2]
Hi. I noticed changes related to migrating to the new version of the Arrow library. 
In merge request was used a new way of creating NonEmptyList using constructor `NonEmptyList(1, listOf(2, 3, 4, 5))`. But I found a better way to do it using function `nonEmptyListOf(1, 2, 3, 4, 5)`. 
I tried to make a pull request to the repo but I don't have access to create a branch.

It's a minor thing, you can just ignore this message and close the issue.

**Comment by ReaktorDTR** [comment]
Please delete this issue.

**Comment by sksamuel** [comment]
You can only close issues not delete.

**Comment by ReaktorDTR** [comment]
From the GitHub docs
> To delete an issue in a repository owned by an organization, an organization owner must enable deleting an issue for the organization's repositories, and you must have admin or owner permissions in the repository.
